Elite_v2/Elite_v2/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .settings import MEDIA_URL, MEDIA_ROOT


urlpatterns = [
    path('elite/', admin.site.urls),
    path('', include('KwetuProduction.urls')),
    path('connexion/', include('accounts.urls')),
]  + static(MEDIA_URL, document_root=MEDIA_ROOT)

Elite_v2/KwetuProduction/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, showArticle, profil, add

app_name = 'kwetu'

urlpatterns = [
    path('', index, name='index'),
    path('<int:produit_id>/', showArticle, name='articleId'),
    path('profil/', profil, name='profil'),
    path('add_Product/', add, name='addProduct')
]

Elite_v2/accounts/urls.py
from django.urls import path
from .views import register, login_user, logout_user, update

app_name = 'accounts'

urlpatterns = [
    path('', login_user, name='connexion'),
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('<int:user_code>/', update, name='update_user')
]

Elite_v2/KwetuProduction/models.py
from django.db import models

class tentreprsie(models.Model):
    nomE = models.CharField(max_length=50, unique=True, null=False, verbose_name="Nom entreprise")
    emailE = models.EmailField(null=False, unique=True, verbose_name="Email")
    descriptionE = models.TextField(blank=True, verbose_name="Description de l'entreprise")

    def __str__(self):
        return self.nomE

class tcathegorie(models.Model):
    nomCat = models.CharField(max_length=50, unique=True, null=False, verbose_name="Cathegorie")

    def __str__(self):
        return self.nomCat

class tproduit(models.Model):
    nomp = models.CharField(max_length=50, unique=True, null=False, verbose_name="Nom produit")
    stock = models.IntegerField(default=1)
    prix = models.IntegerField(default=1)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='produit/', blank=True, null=True)
    idEntrep = models.ForeignKey(tentreprsie,on_delete=models.DO_NOTHING, null=True)
    idCat = models.ForeignKey(tcathegorie, on_delete=models.DO_NOTHING, null=True)

    def __str__(self):
        return self.nomp

Elite_v2/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Client(AbstractUser):
    imgProfil = models.ImageField(upload_to='imgProfil/', blank=True, null=True, verbose_name="Photo de profil")

Elite_v2/KwetuProduction/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import tproduit
import qrcode as qr



def index(request):
    context= tproduit.objects.all()
    return render(request, 'kwetup/index.html', {'articles':context})

def showArticle(request, produit_id):

    articles = tproduit.objects.all()

    context = {'produit': get_object_or_404(tproduit, pk=produit_id),
               'articles':articles}

    return render(request, 'kwetup/showArticle.html', context)

def profil(request):
    return render(request, 'kwetup/profil.html')

def add(request):

    if request.method == "POST":
        pass

Elite_v2/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model, login, logout, authenticate
from .models import Client

User = get_user_model()

# Create your views here.
def register(request):

    if request.method == "POST":
        #traiter le formulaire
        username = request.POST.get("username")
        password = request.POST.get("password")
        imgProfil = request.POST.get("email")
        email = request.POST.get("email")
        first_name = request.POST.get("first_name")
        laste_name = request.POST.get("last_name")

        user = User.objects.create_user(username=username,
                                        password=password,
                                        imgProfil=imgProfil,
                                        email=email,
                                        first_name=first_name,
                                        last_name=laste_name)

        login(request, user)
        return redirect('kwetu:index')

    return render(request, 'accounts/register.html')


def logout_user(request):
    logout(request)
    return redirect('accounts:connexion')


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect('kwetu:index')
    return render(request, 'accounts/login.html')

def update(request,user_code):

    UserCli = Client.objects.all()

    client = get_object_or_404(Client, pk=user_code)
    if request.method == "POST":
        Client.username = request.POST.get('username')
        Client.email = request.POST.get('email')

        client.save()
        return redirect('kwetu:profil')
    return render(request, 'accounts/update_user.html', {'client':client,
                                                         'clients': UserCli})

Elite_v2/KwetuProduction/templates/kwetup/add.html
{% load static %}
{% include './resource2.html' %}

{% block content %}

<h5>Ajouter un nouveau produit</h5>
<form method="POST">
    <label for="name">Nom du produit</label>
    <input type="text" name="nomp" id="nomp">
    <label for="name">Stock</label>
    <input type="text" name="stock" id="stock">
    <label for="name">Prix</label>
    <input type="text" name="prix" id="prix">
    <label for="name">Description</label>
    <input type="text" name="descript" id="descript">
    <label for="name">Image</label>
    <input type="text" name="image" id="image">
    <label for="name">Entreprise</label>
    <input type="text" name="entrep" id="entrep">
    <label for="name">Cathegorie</label>
    <input type="text" name="cat" id="cat">
    <input type="submit" value="Ajouter">
</form>
{% endblock %}
{% include './footer.html' %}

Elite_v2/KwetuProduction/templates/kwetup/footer.html
{% load static %}
    <!--BAS DE PAGE-->
      <div class="card card-cover h-100 text-white bg-dark rounded-3 shadow-lg" style="">

      <div class="row margin">

     <div class="col-lg-3">
      <div class="text-secondary">
        <h5 class="text-start"><br>ELITE 243+</h5>
     </div>
        <p>Avec notre approche intégrée des affaires, de la formation et de la spiritualité, nous nous engageons à offrir des solutions
          complètes et personnalisées à chaque client.
           Rejoignez dès aujourd'hui une communauté d'individus engagés dans la réussite personnelle et professionnelle.</p>
        </div>

      <div class="col-lg-3">
        <h5 class="text-secondary"><br>SOUHAITEZ-VOUS DEVENIR...</h5>
        <a class="nav-link text-light" href="" tabindex="-1">Partenaire</a>
        <a class="nav-link text-light" href="" tabindex="-1">Fournisseur</a>
        <a class="nav-link text-light" href="" tabindex="-1">Acheteur régulier</a>
        <a class="nav-link text-light" href="" tabindex="-1">Acheteur grossiste</a>
      </div>
         <div class="col-lg-3">
            <h5 class="text-secondary"><br>A PROPOS</h5>
            <a class="nav-link text-light" href="" tabindex="-1">Notre équipe</a>
            <a class="nav-link text-light" href="./ELITE_243/nos_objectifs.html" tabindex="-1">Nos objectif</a>
            <a class="nav-link text-light" href="" tabindex="-1">Offre d'emploie</a>
          </div>
         <div class="col-lg-3">
            <h5 class="text-secondary"><br>RESEAU SOCIAUX</h5>
            <p>Pour voir nos publication régulièrement</p>
            <div>
              <a href="">
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="30px" height="35px" src="./ELITE_243/image/fecebook.png" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
              </a>
              <a href="">
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="30px" height="35px" src="./ELITE_243/image/WHATSAPP.png" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
              </a>
              <a href="">
              <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="30px" height="35px" src="./ELITE_243/image/INSTAGRAM.png" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
              </a>
              <a href="">
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="30px" height="35px" src="./ELITE_243/image/TIKTOK.png" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
              </a>
              <a href="">
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="30px" height="35px" src="./ELITE_243/image/telegram.png" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
              </a>
              <a href="">
                <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="30px" height="35px" src="./ELITE_243/image/YOUTUBE.png" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
              </a>
            </div>
          </div>
        </div>
          <a class="nav-link text-secondary text-center" href="#">
            Haut de page<br>
            <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="25px" height="25px" src="{% static '/image/monte.png' %}" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
          </a>
          </div>

        <div class="text-center text-secondary" style="background-color: #000000;">
          <h6><br>&#169 2023 ELITE 243+ tous les drois reservés <br><br></h6>
        </div>
<script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
</body>
</html>

Elite_v2/KwetuProduction/templates/kwetup/head.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">


    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 1200px) {
          .bd-placeholder-img-lg {
           font-size: 3.5rem;
           text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
          }
        }
      </style>

Elite_v2/KwetuProduction/templates/kwetup/index.html
{% load static %}
{% include './resource2.html' %}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-10 mx-auto">
 <div id="myCarousel" class="carousel slide ">
      <div class="carousel-inner text-dark">
        <div  class="carousel-item active" style="height:50%">
            <video loop autoplay muted width="100%" height="100%" class="text-center" src="{% static 'video/pubHead.mp4' %}" type="video/mp4"></video>
        </div>


        <div class="carousel-item">
          <img class="w-100 d-block img-fluid mx-auto" src="{% static 'image/evaAn.png' %}" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
        </div>

      </div>
     <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>
</script>

    </div>
</div>
<!-- AFFICHAGE DE PRODUIT DANS SA PROPRE PAGE -->

<div class="container col-md-12">
<div class="row">
{% for article in articles %}
<div class="col-md-3 container mt-5 card">
<!-- Image du produit -->
    <div class="row mb-4">
        <div class="col-md-8">
            <a href="{% url 'kwetu:articleId' article.id  %}">
            <img src="{{ article.image.url }}" class="img-fluid card-img-top" style="width:90%" alt="{{ article.nomp }}">
            </a>
        </div>
        <div class="col-md-4 text-success">
            <h5>#{{ article.id }}</h5>
        </div>
    </div>
    <!-- Détails du produit -->
    <div class="row">
        <div class="col-md-8 card-title">
        <strong><h6>{{ article.nomp }}</h6></strong>
        </div>
        <!-- Prix et achat -->
        <div class="col-md-4">
        <h5 class="text-success">{{ article.prix }} $</h5>
        <p class="text-success">Stock: {{ article.stock }}</p>
        </div>
         <strong>
            <a class=" link-success text-decoration-none" href="{% url 'kwetu:articleId' article.id  %}">Voir en detaille...</a>
        </strong>
    </div>
</div>
    {% endfor %}
</div>
</div>
</div>

<hr>
<div>
    <h4>Django est puissant </h4>
</div>
{% endblock %}
{% include './footer.html' %}

Elite_v2/KwetuProduction/templates/kwetup/profil.html
{% load static %}
{% include './resource2.html' %}

{% block content %}

<div class="container mt-5">
    {% if user.is_authenticated %}

        <div class="row">
            <div class="col-md-6 me-auto">
                <div class="card col-md-12">
                    <div class="row">
                        <a class="text-end col-md-4 me-auto" id="qrcode"></a>
                        <a class="mx-auto col-md-6 nav-link link-dark">
                            <h5>Profil: {{ user.username }} {{ user.first_name }}</h5>
                        </a>
                    </div>
                    {% if user.imgProfil %}
                        <img class="rounded-5 bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="35%" height="20%" src="{{ user.imgProfil.url }}" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
                    {% else %}
                        <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="35%" src="{% static 'image/defaultProfil.png' %}" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
                    {% endif %}
                    <div class="card-body text-center">
                        <h5 class="card-title">{{ user.username }} {{ user.last_name }} {{ user.first_name }}</h5>
                        <p class="card-text">{{ user.email }}</p>
                        <a href="#" class="btn btn-primary small">Modifier la photo</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 me-auto">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Modifier le profil</h5>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{% url 'kwetu:profil' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="nom">Nom</label>
                                <input class="form-control" type="text" value="{{ user.username }}">
                            </div>
                            <div class="form-group">
                                <label for="prenom">Prénom</label>
                                <input class="form-control" type="text" value="{{ user.last_name }}">
                            </div>
                            <div class="form-group">
                                <label for="poste">Prenom</label>
                                <input class="form-control" type="text" value="{{ user.first_name }}">
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input class="form-control" type="text" value="{{ user.email }}"><br>
                            </div>
                            <div class="form-group">
                                <br>
                                 <button class="btn btn-primary" type="submit">Modifier</button>
                                <br><br>
                            </div>
                        </form>
                        <div class="card-header">
                            <h6>Autres info consernant le vente et achat: </h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>



    <!-- Incluez qrcode.js (ou une autre bibliothèque de génération de code QR) -->
    <script src="https://cdn.rawgit.com/davidshimjs/qrcodejs/gh-pages/qrcode.min.js"></script>
    <script>
        // Exemple de génération de code QR avec l'ID de l'utilisateur
        const userId = {{ user.id }}; // Remplacez par l'ID réel de l'utilisateur
        const qrcode = new QRCode(document.getElementById("qrcode"), {
            text: `${userId}`,
            width: 80,
            height: 80
        });
    </script>

   {% endif %}
    <!-- Modals similaires pour Prénom, Poste et Email -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock %}
{% include './footer.html' %}

Elite_v2/KwetuProduction/templates/kwetup/resource2.html
{% include './head.html' %}
{% load static %}
<title>Bienvenu::elite243+</title>
<body>
<header>
<div class="" style="background-color: #000000;">
  <div class="container-fluid">
    <div class="row">
    <div class="col-6 me-auto">
     <BUtton class="btn btn-warning text-start" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">
        <a  href="#" class="navbar-toggler-icon">
            <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" src="{% static 'image/menu.png' %}" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
        </a>
     </BUtton>
    </div>

      <div class="col-6 me-auto text-end text-warning">
          {% if  user.is_authenticated %}
           <strong><a class="link-light text-decoration-none" href="{% url 'kwetu:profil' %}">{{ user.username }}</a></strong>
              {% if user.imgProfil %}
                 <img class="rounded-circle bd-placeholder-img bd-placeholder-img-lg featurette-image " width="5%" src="{{ user.imgProfil.url }}" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
              {% else %}
                 <img class="rounded-circle bd-placeholder-img bd-placeholder-img-lg featurette-image " width="5%" src="{% static 'image/defaultProfil.png' %}" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
              {% endif %}
          {% else %}
              <strong><a class="link-light text-decoration-none" href="{% url 'accounts:register' %}">S'inscrir</a></strong>
          {% endif %}
      </div>

    </div>
  </div>

    <div class="offcanvas offcanvas-start bg-light" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
        <div class="offcanvas-header bg-secondary" >
            <div class="container" id="offcanvasScrollingLabel">
              <div class="row ">
                <div class="col">
                  {% if user.imgProfil %}
                    <img class="rounded-circle bd-placeholder-img bd-placeholder-img-lg featurette-image  mx-auto" height="15%" width="15%" src="{{ user.imgProfil.url }}" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
                  {% else %}
                     <img class="rounded-circle bd-placeholder-img bd-placeholder-img-lg featurette-image mx-auto" width="15%" src="{% static 'image/defaultProfil.png' %}" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><fill="#eee"/></img>
                  {% endif %}
                </div>
              </div>
            </div>
            <button type="button" class="btn-close btn-light text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>

        <div class="offcanvas-header" style="margin: 20px;">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <h3>Nos produits</h3>
              <li class="nav-item">
                <a class="nav-link text-dark" aria-current="page" href="{% url 'kwetu:index' %}">
                   Acceuil
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'kwetu:index' %}">
                  Nos objectifs
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'kwetu:index' %}" tabindex="-1">
                  Nos services
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'kwetu:index' %}" tabindex="-1">
                  A propos de nous
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'kwetu:index' %}" tabindex="-1">
                  Contact
                </a>
              </li>
                <li>
                    <a class="nav-link text-dark" href="{% url 'accounts:logout' %}">
                        Deconnexion
                    </a>
                </li>
            </ul>

          </div>
    </div>
</div>
</header>
<main>
            <div class="nav-scroller py-1 mb-2 blog-header bg-dark">
              <nav class="nav nav-item d-flex justify-content-between">
                  <a class="p-2 link-light text-decoration-none" href="{% url 'kwetu:index' %}"> <h6>Acceuil</h6> </a>
                  <a class="p-2 link-light text-decoration-none" href="{% url 'kwetu:index' %}"> <h6>Nouveau produit</h6> </a>
                  <a class="p-2 link-light text-decoration-none" href="{% url 'kwetu:index' %}"> <h6>Vos achats</h6> </a>
                  <a class="p-2 link-light text-decoration-none" href="{% url 'kwetu:index' %}"> <h6>Genius edition</h6> </a>
                  <a class="p-2 link-light text-decoration-none" href="{% url 'kwetu:index' %}"> <h6>Evangile pour tous</h6> </a>
                  <a class="p-2 link-light text-decoration-none" href="{% url 'kwetu:index' %}"> <h6>Entreprise</h6></a>
              </nav>
            </div>
    <div id="loader" class="spinner-border text-primary" role="status" style="position:fixed; top:50%;left:50%; transform:translate(-50%, -50%)">
        <img class="img-fluid mx-auto" src="{% static 'image/el243.png' %}" alt="{{ user.username }}">
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", function(event){
        document.getElementById('loader').style.display='none';
        });
    </script>
  {% block content %}

  {% endblock %}
</main>

Elite_v2/KwetuProduction/templates/kwetup/showArticle.html
{% load static %}
{% include './resource2.html' %}

{% block content %}
<!-- AFFICHAGE DE PRODUIT DANS SA PROPRE PAGE -->

<div class="container col-md-12">
<div class="row">
<div class="col-md-2 container mt-5">
<!-- Image du produit -->
    <div class="row mb-4">
        <div class="col-md-8">
        <img src="{{ produit.image.url }}" class="img-fluid" alt="{{ produit.nomp }}">
        </div>
    </div>
    <!-- Détails du produit -->
    <div class="row">
        <div class="col-md-8">
        <h4>{{ produit.nomp }}</h4>
        <p class="lead">{{ produit.description }}</p>
        </div>
        <!-- Prix et achat -->
        <div class="col-md-4">
        <h5 class="text-success">{{ produit.prix }} $</h5>
        <p class="text-success">Stock: {{ article.stock }}</p>
        <p class="text-success">Entreprise: {{ produit.idEntrep }}</p>
        <p class="text-success">Cathegorie: {{ produit.idCat }}</p>
        <button class="btn btn-primary btn-small">Acheter</button>
        </div>
    </div>
</div>

</div>
</div>

<div class="col-12-md text-center">
    <a class="nav-link link-success" href="{% url 'kwetu:index' %}"><<<< Retour</a>
</div>
{% endblock %}
{% include './footer.html' %}

Elite_v2/accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LOGIN::EVANGELISATION</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="text-light bg-dark">
        <h6 class="text-center">Welcome</h6>
    </div>
    <br><br>

    <div class="row">
        <div class="col-md-4 mx-auto"  style="border: 5px solid teal">
            <h4 class="text-center text-success">Connexion</h4>
            <img class="img-fluid" src="{% static 'image/eva.png' %}" alt="LOGO" width="50%" style="margin-left: 30%">
            <form method="POST">
                {% csrf_token %}
                <label for="username">Nom</label>
                <input class="form-control" type="text" name="username" id="username"><br><br>
                <label for="password">Password</label>
                <input class="form-control" type="password" id="password" name="password"><br><br>

                <button type="submit" class=" btn btn-success text-light" style="margin-left: 25%">
                    Connexion
                </button>

                <a class="btn btn-info link-dark text-decoration-none" href="{% url 'accounts:register' %}">
                    S'inscrit ?
                </a>
                <br><br>
            </form>
        </div>
    </div>
    </div>
</body>
</html>

Elite_v2/accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SINGUP::EVANGELISATION</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="text-light bg-dark">
        <h6 class="text-center">Welcome</h6>
    </div>
    <br><br>

    <div class="row">
        <div class="col-md-4 mx-auto"  style="border: 5px solid green">
            <h4 class="text-center text-success">S'inscrire</h4>
            <img class="img-fluid" src="{% static 'image/eva.png' %}" alt="LOGO" width="50%" style="margin-left: 30%">
            <form method="POST">
                {% csrf_token %}
                <label for="username">Nom</label>
                <input class="form-control" type="text" name="username" id="username"><br>
                <label for="password">Post-nom</label>
                <input class="form-control" type="text" id="last_name" name="last_name"><br>
                <label for="password">Prenom</label>
                <input class="form-control" type="text" id="first_name" name="first_name"><br>
                <label for="password">Password</label>
                <input class="form-control" type="password" id="password" name="password"><br>
                <label for="password">Email</label>
                <input class="form-control" type="email" id="email" name="email"><br>
                <label for="password">Photo de profil</label>
                <input class="form-control" type="file" id="imgProfil" name="imgProfil"><br>


                <button type="submit" class=" btn btn-success text-light" style="margin-left: 30%">
                    S'inscrire
                </button>
                <button class=" btn btn-info" style="margin-left: 5%">
                    <a class="link-dark text-decoration-none" href="{% url 'accounts:connexion' %}">Déja inscrit ?</a>
                </button><br><br>
            </form>
        </div>
    </div>
    </div>
</body>
</html>

Elite_v2/accounts/templates/accounts/update_user.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>


<div class="col-md-6 me-auto">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Modifier le profil</h5>
                    </div>
                    <div class="card-body">
                        {% for client in clients %}
                        <form method="POST" action="{% url 'accounts:update_user' client.id %}">
                            {% endfor %}
                            {% csrf_token %}

                                <label for="nom">Nom</label>
                                <input class="form-control" type="text" value="{{ user.username }}" name="username" id="username"><br>

                                <label for="prenom">Prénom</label>
                                <input class="form-control" type="text" value="{{ user.last_name }}" name="last_name" id="last_name">

                                <label for="poste">Prenom</label>
                                <input class="form-control" type="text" value="{{ user.first_name }}" name="first_name" id="first_name">

                                <label for="email">Email</label>
                                <input class="form-control" type="text" value="{{ user.email }}" name="email" id="email"><br>
                                <br>
                                 <button class="btn btn-primary" type="submit">Modifier</button>
                                <br><br>

                        </form>

                    </div>
                    </div>
                </div>
</div>
</body>
</html>